version: '3.8'

services:
  app:
    build: .
    image: skaymant/restservice
    depends_on:
      - postgres
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    restart: always
    networks:
      - my_network

  postgres:
    build: ./database
    image: skaymant/postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - datapg:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  datapg: